### PR TITLE
add support for version

### LINKED ISSUE #100: --version
support for --version was dropped between 0.7 and 0.8?

--version is useful in a lot of ways for CI and keeping installed tools up to date.

### PR DESCRIPTION
**Pull request by rob-solana**
fixes #100

### CODE REVIEW

**Comment by tarcieri** [comment]
Thanks!

**Comment by rob-solana** [comment]
anytime.  I hope to see a 0.8.1 release soon so I can turn --version back on in our tree

https://github.com/solana-labs/solana/pull/5611/files#diff-4b5263e29d55962afaf13a723bb3d2b9R21

**Comment by tarcieri** [comment]
Will try to cut one soon when I'm not busy with RustConf 😉

**Comment by rob-solana** [comment]
maybe say hi to https://github.com/garious while there ;)

**Comment by tarcieri** [comment]
@rob-solana released in #102 

(also said hi to garious)

**Pull request merged**
