### PR TITLE
move smol_str to dependencies from dev-dependencies

### PR DESCRIPTION
**Pull request by galich**
i've tried `cargo install --git https://github.com/galich/cargo-audit.git --branch move-smol-to-deps` and it was working with Rust 1.44

### CODE REVIEW

**Comment by galich** [comment]
Checks failed with

> error: caused by: failed to make network request

@tarcieri I can not see any way to restart it, any suggestion will be appreciated

**Comment by tarcieri** [comment]
@galich merged. can you try `cargo install` again?

**Comment by galich** [comment]
@tarcieri it works now

**Comment by bsclifton** [comment]
@tarcieri will there be a new version published on crates.io?

**Comment by tarcieri** [comment]
v0.12.1 is released

**Pull request merged**
